### ISSUE TITLE
Smartmi Humidifier v1/v2 / 3.1.26

### ISSUE THREAD

**Issue by zawinull** [jghaanstra/com.xiaomi-miio#198]
“Device is unreachable: result_extra_props_cb1 is not defined”

ec412df1-1fa7-46f1-a449-9cc3b6c652ae

**Comment by jghaanstra** [comment]
Fixed with 3.1.27 which is now available in test.

**Comment by zawinull** [comment]
3.1.27 - it works, but the humidity data is still wrong and the exact temperature data appears for a few seconds and then disappears.
 
 
![image](https://user-images.githubusercontent.com/53702811/235161728-7f661da9-ed5c-4405-8dfc-dc25ef32f3c2.png)
