### ISSUE TITLE
New update 3.2.9 results in crashing my smart fan.

### ISSUE THREAD

**Issue by pjmpessers** [jghaanstra/com.xiaomi-miio#212]
I now get a red exclamation mark. I made a error log?

See 7e25dd34-75a8-4a5a-aca4-bab53fb25af6

**Comment by jghaanstra** [comment]
What model identifier and does your model support setting the angle of the fan?

**Comment by pjmpessers** [comment]
Thanks for the quick response. It is the dmaker.fan.1c. I while ago i contacted you that it was not possible to get it to swing with the action card. That was solved. But now it is giving me a red exclamation mark.

**Comment by jghaanstra** [comment]
Will fix it with the next release.

**Comment by pjmpessers** [comment]
Thank you, Jelger. But this has also problems. And i already knew that, because it tested this before. Is it possible to get the v3.2.7?

**Comment by jghaanstra** [comment]
https://github.com/jghaanstra/com.xiaomi-miio/tree/68953c46a08a523378866ecda083ab9c13ec293c

**Comment by pjmpessers** [comment]
Thank you. Sadly enough sideloading it results in a app crash. It seems athom has done something with the cli. Ooooh well. Just need to be patience and wait for the update. In the mean time, thanks for the support.

**Comment by pjmpessers** [comment]
For what i have seen so far. When i setup the fan again it is possible to controle it and, switch off/on, speed adjustment, etc. But after a few seconds it stops.

**Comment by jghaanstra** [comment]
I'm aware. I already fixed it locally but I'm working on other stuff as well before I can release. But I pushed the change as part of release 3.2.10 to Github so you can install it through CLI.

**Comment by pjmpessers** [comment]
Your quick. Thank you. Tried to sideload it. Even when i done npm install. It installs without a glitch to homey, but on homey pro 2023 it crashes. I think athom has done something to the cli. I even downloaded node.js v18.16.0(x64) to match it with homey, but no go.
Aaah well. I just need to be patient untill you uploaded it to homey store. :-)

**Comment by jghaanstra** [comment]
This issue should be fixed with release 3.2.10 which is now in test and awaiting approval from Athom to go live. Please test.

https://homey.app/a/com.xiaomi-miio/test/

**Comment by pjmpessers** [comment]
Sadly the problem still exists. Most of the time it is disconnected. And without a reason (or not from what i know off it is connected and except a action. But this is rarely. 

See aea446c1-4a31-4726-88ad-40a142e61eca

**Comment by pjmpessers** [comment]
![Screenshot_20230617_103029_Homey](https://github.com/jghaanstra/com.xiaomi-miio/assets/34476404/821bec88-8cd5-494d-bba2-763af51e3c31)

**Comment by pjmpessers** [comment]
![Screenshot_20230617_103231_Homey](https://github.com/jghaanstra/com.xiaomi-miio/assets/34476404/5834824f-55aa-46db-8e9d-27a25971b98a)


After about a minuut everything is normale again. And after a few seconds it's crashing again.

**Comment by jghaanstra** [comment]
Did you re-pair the device before testing?

**Comment by pjmpessers** [comment]
I did it just now. I could start the fan, but then it crashed again. Must i choose 
![Screenshot_20230617_123631_Homey](https://github.com/jghaanstra/com.xiaomi-miio/assets/34476404/52e20456-b6f0-4831-a2a9-f5eba9a6a340)
?

**Comment by pjmpessers** [comment]
I tryed all the 5 options. But none of them is working stable. :-)

**Comment by jghaanstra** [comment]
See my previous message.

> I think I found another issue and will fix it with the next release.

There is absolutely no use in testing any other driver. They are stable but not for your model.

**Comment by pjmpessers** [comment]
I lost that comment. So from what i understand it will be fixed in v3.2.11? If that is the case, great. I will wait for that release. Thanks again.

**Comment by pjmpessers** [comment]
Great. V3.2.11 fixed my problem. Thank you.

**Comment by pjmpessers** [comment]
⁹

**Comment by jghaanstra** [comment]
Good to hear and thanx for the donation ...

**Comment by pjmpessers** [comment]
Your welcome. Glad it works again.

**Comment by pjmpessers** [comment]
Sometimes my fan isn't responding in flow or at device tab giving error:"usr ack timeout" or something similar. 
Send feedback 27c1b7ea-b30f-4f01-a4ef-873503789533

**Comment by jghaanstra** [comment]
> Sometimes my fan isn't responding in flow or at device tab giving error:"usr ack timeout" or something similar. Send feedback 27c1b7ea-b30f-4f01-a4ef-873503789533

Welcome to the world of reversed engineered API. This is not an issue with the Homey app but with the network connection. Not something I can fix.
