### ISSUE TITLE
Roidmi Eve breaks after successful pairing

### ISSUE THREAD

**Issue by enyineer** [jghaanstra/com.xiaomi-miio#220]
Thank you for your great contribution with this app. I do unfortunately have problems pairing my Roidmi Eve Vacuum Robot with your app.

I first chose the Roidmi Eve device in the supported devices of your app
![roidmi_1](https://github.com/jghaanstra/com.xiaomi-miio/assets/27201677/efbd282f-6512-4455-a3fc-8be1e442ea5b)

I then retrieved it's Mi Home token
![roidmi_2](https://github.com/jghaanstra/com.xiaomi-miio/assets/27201677/e0ffac65-2bc1-4a6a-b0f4-1bb144fdc573)

The token and IP were then provided to the setup wizard
![roidmi_3](https://github.com/jghaanstra/com.xiaomi-miio/assets/27201677/8dcb1fb1-8fcf-4180-85b6-b08e454cc3ba)

For a few second it seems to be connected, but after a few seconds it bugs out with an error message
![roidmi_4](https://github.com/jghaanstra/com.xiaomi-miio/assets/27201677/c9150a73-0aa0-43a8-b64b-8f3bb8f22eab)

It looks like the app was able to get some device stats though, so the connection must have worked in general
![roidmi_5](https://github.com/jghaanstra/com.xiaomi-miio/assets/27201677/6d77c97d-fa2c-489d-a544-582823645f13)

Do you have any idea how and if that can be fixed? I might even contribute if I find out what's causing this.

Diagnostics report id is 4a06fcb3-ca80-4f38-863d-680e566b4f6b

Thanks in advance!

**Comment by jghaanstra** [comment]
It's a bug. I'll fix it with the next release.

**Comment by jghaanstra** [comment]
Should be fixed now. Please report back here if you experience issues.

**Comment by enyineer** [comment]
Do I have to re-add the vacuum or is the update not published to the App Store yet? I do currently still get the same error.

**Comment by jghaanstra** [comment]
Can you send me another diagnostic report. Re-pairing should not be needed, apparently the bug is not fixed or there is another bug present.

**Comment by enyineer** [comment]
Sure. New Diagnostics Report ID is: cae50e0b-0459-4b93-9807-82e90d015a8e

**Comment by jghaanstra** [comment]
Thanx, another fix will come with the next release.

**Comment by jghaanstra** [comment]
Could you re-test this with release 3.2.12 which is currently pending approval in the test channel.

https://homey.app/a/com.xiaomi-miio/test/

**Comment by enyineer** [comment]
The error seems to be gone now! Thank you 👍
However, when starting the cleaning and afterwards selecting "Docked" or "Charging" to get the robot to recharge at the station it unfortunately seems to not react and the following error is thrown:

![Screenshot_20230731-210535](https://github.com/jghaanstra/com.xiaomi-miio/assets/27201677/683ce6b7-c1c9-4f7e-a9b4-d30ba18c8d77)

This is not too bad because we can start it via Flows, but it would be great if you could have a look into that 🙂

Diagnostics report ID is: dd307d98-d825-415d-bab8-33a708a245ef

**Comment by jghaanstra** [comment]
Try rebooting Homey and try again. The error might just be a networking error.

**Comment by enyineer** [comment]
I'm still getting the same bug after the upgrade to v10 (and thus a restart).

**Comment by jghaanstra** [comment]
I will fix that with the next release.

**Comment by jghaanstra** [comment]
This has been fixed with release 3.2.13 which is pending approval. Please use the test version to test it.

https://homey.app/a/com.xiaomi-miio/test/

**Comment by jghaanstra** [comment]
Closing this due to lack of feedback.
